on: push
name: 🚀 Deploy website to MTWSNC server
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest files
      uses: actions/checkout@v4

    - name: 📂 Upload files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 167.88.45.24
        username: mtwsdawah
        password: ${{ secrets.password }}
        protocol: ftps
        server-dir: web/dawah.mtws.one/public_html/
        state-name: .github-log.json
        log-level: standard
